name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      CI_ENV: true
    steps:
      - uses: actions/checkout@v6
      - name: Set up Java 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
      - name: Formatting
        run: clojure -M:cljfmt check
      - name: Linting
        run: clojure -M:clj-kondo --lint src --lint test --lint dev

  test:
    runs-on: ubuntu-latest
    env:
      CI_ENV: true
    steps:
      - uses: actions/checkout@v6
      - name: Set up Java 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
      - name: Set up Node 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run tests
        run: yarn test
